### ISSUE TITLE
How do I obtain my private keys on this wallet for the upcoming fork with Zen?

### ISSUE THREAD

**Issue by RDollarSign** [zencashio/eleos#13]
I can't figure out how to obtain my private key to import into the Zen wallet to get my equal Zen. The eleos design is complicated, but it's the only wallet that works on MacOS for me.

**Comment by phieti** [comment]
Id like to know too

**Comment by Kahana82** [comment]
This explains how to do a ZClassic export -> ZEC import with eleos wallet:
https://blog.zencash.io/transfer-zclassic-to-eleos-wallet-and-copy-private-keys
Off course this will do nothing but after the Zen launch just do the same, except import into the Zen wallet (instead of ZEC like in the example).

**Comment by LukasBures** [comment]
you can follow instruction for Eleos 0.0.5 version on release page
